[package]
name = "rust-exec"
version = "0.1.0"
authors = ["MROS <yc1043@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cita_trie = { path = "./cita-trie" }
hasher = "0.1.2"
